---
output:
  word_document:
    fig_width: 4
    keep_md: yes
  html_document: default
  header-includes:
  - \usepackage{inputenc}
  - \usepackage{unicode-math}
  pdf_document:
    keep_tex: yes
    latex_engine: xelatex
---
```{r echo=FALSE, eval=TRUE, warning=FALSE, message=FALSE}
library(Rceattle)
library(lubridate)

# Load models and code
source("ESP_Figure_Code.R")
source("ESR_Figure_Code.R")
load("Models/GOA_23_1_1_mod_list.RData")

# Get model objects for use below
ceattle_esr_model <- mod_list_all[[3]]
years <- ceattle_esr_model$data_list$styr:2024
thisYr <- years[length(years)]

# Uncertainty of key parameters
b_eaten_as_prey <- ceattle_esr_model$quantities$B_eaten_as_prey
b_eaten_as_prey_sd <- replace(b_eaten_as_prey, values = ceattle_esr_model$sdrep$sd[which(names(ceattle_esr_model$sdrep$value) == "B_eaten_as_prey")])

M_at_age <- ceattle_esr_model$quantities$M
M_at_age_sd <- replace(M_at_age, values = ceattle_esr_model$sdrep$sd[which(names(ceattle_esr_model$sdrep$value) == "M")])


# Mortality rates and means/peaks
peak_M <- c()
avg_M <- c()
avg_Age1_Beaten <- c()
avg_Beaten <- c()
avg_Ration <- c()
terminal_M <- c()
terminal_M_sd <- c()
terminal_Age1_Beaten <- c()
terminal_Age1_Beaten_sd <- c()
terminal_Beaten <- c()
terminal_Ration <- c()
peak_M_ind <- c()
peak_M_years <- c()
ind <- 1
for(sp in 1:3){
  for(sex in 1:ceattle_esr_model$data_list$nsex[sp]){
    
    # Sex-specific M
    peak_M[ind] <- max(ceattle_esr_model$quantities$M[sp,sex,1,1:length(years)])
    avg_M[ind] <- mean(ceattle_esr_model$quantities$M[sp,sex,1,1:length(years)])
    terminal_M[ind] <- ceattle_esr_model$quantities$M[sp,sex,1,length(years)]
    terminal_M_sd[ind] <- M_at_age_sd[sp,sex,1,length(years)]
    terminal_Age1_Beaten[ind] <- (ceattle_esr_model$quantities$B_eaten_as_prey[sp,sex,1,length(years)])
    terminal_Age1_Beaten_sd[ind] <- b_eaten_as_prey_sd[sp,sex,1,length(years)]
    
    peak_M_ind[ind] <- which(ceattle_esr_model$quantities$M[sp,sex,1,1:length(years)] == peak_M[ind])
    peak_M_years[ind] <- years[peak_M_ind[ind]]
    ind <- ind+1
  }
  
  # B-eaten
  avg_Beaten[sp] <- mean(apply(ceattle_esr_model$quantities$B_eaten_as_prey[sp,,,1:length(years)], 3, sum))
  terminal_Beaten[sp] <- sum(ceattle_esr_model$quantities$B_eaten_as_prey[sp,,,length(years)])
  
  avg_Age1_Beaten[sp] <- mean(colSums(ceattle_esr_model$quantities$B_eaten_as_prey[sp,,1,1:length(years)]))
  terminal_Age1_Beaten[sp] <- sum(ceattle_esr_model$quantities$B_eaten_as_prey[sp,,1,length(years)])
  
  # Ration
  ration <- weighted_ration(ceattle_esr_model, spp = sp, endyr = 2022, minage = 4)
  avg_Ration[sp] <- mean(ration)
  terminal_Ration[sp] <- ration[length(ration)]
}

# Percent change in mortality
prcnt_change <- round(abs(100 * (terminal_M-peak_M)/peak_M),2)

# Format some values
avg_Beaten <- format(round(avg_Beaten, 0), scientific = FALSE, big.mark = ",")
terminal_Beaten <- format(round(terminal_Beaten, 0), scientific = FALSE, big.mark = ",")

avg_Age1_Beaten <- format(round(avg_Age1_Beaten, 0), scientific = FALSE, big.mark = ",")
terminal_Age1_Beaten <- format(round(terminal_Age1_Beaten, 0), scientific = FALSE, big.mark = ",")
terminal_Age1_Beaten_sd <- format(round(terminal_Age1_Beaten_sd, 0), scientific = FALSE, big.mark = ",")
```

```{r chunk3, echo=FALSE, eval=TRUE, include=FALSE}
sclr<-1

cols <- nmfspalette::nmfs_palette("oceans")(3)[3:2]

# Figure 1: Time series of biomass
jpeg(file="Results/ATF_ESP_Fig1.jpg",height=3.5*sclr, width=4.5*sclr, units="in",res=350)
plot_biomass(list(mod_list_all[[1]], mod_list_all[[3]]), line_col = cols, species = 2, model_names = "Single-spp CEATTLE", "Multi-spp CEATTLE")
legend("topright",c( "Single-spp CEATTLE", "Multi-spp CEATTLE"), bty = "n", col = cols, lwd = 2)
mtext(side = 2, "Age-1+ biomass (million mt)", line = 2)
dev.off()

# Figure 2: Time series of mortality
jpeg(file="Results/ATF_ESP_Fig2_age1.jpg",height=5*sclr, width=4.5*sclr, units="in",res=350)
plot_m_at_age(list(mod_list_all[[1]], mod_list_all[[3]]), age = 1, species = 2,  line_col = cols, lty = c(2,1))
dev.off()

jpeg(file="Results/ATF_ESP_Fig2_age2.jpg",height=5*sclr, width=4.5*sclr, units="in",res=350)
plot_m_at_age(list(mod_list_all[[1]], mod_list_all[[3]]), age = 2, species = 2,  line_col = cols, lty = c(2,1))
dev.off()

jpeg(file="Results/ATF_ESP_Fig2_age3.jpg",height=5*sclr, width=4.5*sclr, units="in",res=350)
plot_m_at_age(list(mod_list_all[[1]], mod_list_all[[3]]), age = 3, species = 2,  line_col = cols, lty = c(2,1))
dev.off()

# Figure 3: Time series of biomass consumed
jpeg(file="Results/ATF_ESP_Fig3.jpg",height=5*sclr, width=4.5*sclr, units="in",res=350)
plot_b_eaten(mod_list_all[[3]], line_col = cols[2], species = 2)
dev.off()


# Figure 4: Time series of annual ration
jpeg(file="Results/ATF_ESP_Fig4.jpg",height=5*sclr, width=4.5*sclr, units="in",res=350)
plot_ration(mod_list_all[[3]], line_col = cols[2], species = 2, minage = 4)
dev.off()

# Figure 5: Combined plots
# - Pollock
jpeg(file="Results/Pollock_ESP_Fig5.jpg",height=8*sclr, width=4.5*sclr, units="in",res=350)
ESP_plot(msModel = mod_list_all[[3]], ssModel = mod_list_all[[1]], age = 1, minage = 4, endyr = 2023, species = 1)
dev.off()

# - Cod
jpeg(file="Results/Cod_ESP_Fig5.jpg",height=8*sclr, width=4.5*sclr, units="in",res=350)
ESP_plot(msModel = mod_list_all[[3]], ssModel = mod_list_all[[1]], age = 1, minage = 4, endyr = 2023, species = 3)
dev.off()

# - Atf
jpeg(file="Results/ATF_ESP_Fig5.jpg",height=8*sclr, width=4.5*sclr, units="in",res=350)
ESP_plot(msModel = mod_list_all[[3]], ssModel = mod_list_all[[1]], age = 1, minage = 4, endyr = 2023, species = 2)
dev.off()
```	



# Indices
```{r}

# Annual biomass of GOA Pacific cod consumed by predators
# Annual biomass of GOA pollock consumed by predators
# Annual ration of GOA Pacific cod
# Annual ration of GOA pollock
# Total natural mortality (m1+m2) of age-1 GOA Pacific cod
# Total natural mortality (m1+m2) of age-1 GOA pollock 

# -- Pollock and cod
for(i in c(1,3)){
  sp = i
  
  spname = mod_list_all[[3]]$data_list$spnames[sp]
  nages <- mod_list_all[[3]]$data_list$nages[sp]
  
  Matage1 = data.frame(Year = years,
                       MS_M = mod_list_all[[3]]$quantities$M[sp,1,1,1:length(years)], 
                       SS_M = mod_list_all[[1]]$quantities$M[sp,1,1,1:length(years)])
  
  Biomass = data.frame(Year = years,
                       SS_Biomass = mod_list_all[[1]]$quantities$biomass[sp,1:length(years)],
                       SS_SSB = mod_list_all[[1]]$quantities$biomassSSB[sp,1:length(years)],
                       
                       MS_Biomass = mod_list_all[[3]]$quantities$biomass[sp,1:length(years)],
                       MS_SSB = mod_list_all[[3]]$quantities$biomassSSB[sp,1:length(years)]
  )
  
  B_eaten = data.frame(Year = years,
                       Biomass_eaten_as_prey = colSums(mod_list_all[[3]]$quantities$B_eaten_as_prey[sp,1,,1:length(years)]))
  
  Ration = data.frame(Year = years,
                      `Age4plusTotal` = weighted_ration(ceattle_esr_model, spp = sp, endyr = 2024, minage = 4),
                      `Age1plusTotal` =weighted_ration(ceattle_esr_model, spp = sp, endyr = 2024, minage = 1)
  )
  
  
  # Indices to share
  library(writexl)
  write_xlsx(
    list(Age1_M = Matage1,
         Biomass = Biomass,
         B_eaten = B_eaten,
         Ration = Ration
    )
    ,paste0("Results/", spname, "ESP Indices.xlsx")
    )
}




# -- ATF
nages <- mod_list_all[[3]]$data_list$nages[2]

Female_M = cbind(years,t(mod_list_all[[3]]$quantities$M[2,1,,1:length(years)]), data.frame(M = mod_list_all[[1]]$quantities$M[2,1,1,1:length(years)]))

colnames(Female_M) <- c("Year", paste0("Multi-spp M Age_",1:nages), "Single-spp M")

Male_M = cbind(years,t(mod_list_all[[3]]$quantities$M[2,2,,1:length(years)]), data.frame(M = mod_list_all[[1]]$quantities$M[2,2,1,1:length(years)]))

colnames(Male_M) <- c("Year", paste0("Multi-spp M Age_",1:nages), "Single-spp M")

# Indices to share
library(writexl)
write_xlsx(
  list(Female_M = Female_M,
       Male_M = Male_M,
       
       Biomass = data.frame(Year = years,
                            SS_Biomass = mod_list_all[[1]]$quantities$biomass[2,1:length(years)],
                            SS_SSB = mod_list_all[[1]]$quantities$biomassSSB[2,1:length(years)],
                            
                            MS_Biomass = mod_list_all[[3]]$quantities$biomass[2,1:length(years)],
                            MS_SSB = mod_list_all[[3]]$quantities$biomassSSB[2,1:length(years)]
       ),
       
       B_eaten = data.frame(Year = years,
                            Biomass_eaten_as_prey_F = colSums(mod_list_all[[3]]$quantities$B_eaten_as_prey[2,1,,1:length(years)]),
                            Biomass_eaten_as_prey_M = colSums(mod_list_all[[3]]$quantities$B_eaten_as_prey[2,2,,1:length(years)]),
                            Total_biomass_eaten_as_prey = colSums(mod_list_all[[3]]$quantities$B_eaten_as_prey[2,2,,1:length(years)]) + colSums(mod_list_all[[3]]$quantities$B_eaten_as_prey[2,1,,1:length(years)])),
       
       Ration = data.frame(Year = years,
                           `4+Female` = colSums(mod_list_all[[3]]$quantities$ration[2,1,4:21,1:length(years)]),
                           `4+Male` = colSums(mod_list_all[[3]]$quantities$ration[2,2,4:21,1:length(years)]),
                           `4+Total` = colSums(mod_list_all[[3]]$quantities$ration[2,1,4:21,1:length(years)]) + colSums(mod_list_all[[3]]$quantities$ration[2,2,4:21,1:length(years)])
       )
  )
  ,"Results/ATF ESP Indices.xlsx")



```